- name: Install MongoDB 3.2
  hosts: all
  become: true
  tasks:
    - name: Update repo
      apt:
              update cach: true
              name: mongodb
              state: present
    - name: Enable mongodb
      systemd:
        name: mongodb
        enabled: yes
      notify:
      - restart mongodb
    - name: Configure service supervisor
      systemd:
        name: mongod
        enabled: yes

  handlers:
  - name: restart mongodb
    systemd:
      name: mongodb
      state: restarted
